### ISSUE TITLE
Not working with laravel 5.8 registering

### ISSUE THREAD

**Issue by Janiaje** [davekelly/static-generator#4]
As mentioned in the docs I added the `Davekelly\StaticGenerator\StaticGeneratorServiceProvider::class` to the end of the `'providers'` array.
The followin error is returned on running anything afterwards:
```
/home/xyz/projectDir>php artisan route:list

In StaticGeneratorServiceProvider.php line 21:

  Call to undefined method Davekelly\StaticGenerator\StaticGeneratorServiceProvider::package()
```

**Comment by davekelly** [comment]
@Janiaje This generator was originally written for Laravel 4, and hasn't been updated for Laravel 5.
